### PR TITLE
Add Nix package run option

### PR DESCRIPTION
**Pull request by petertrotman**
Currently available at my nixpkgs fork, but hopefully it will be merged upstream soon.

### CODE REVIEW

**Comment by petertrotman** [comment]
I should mention that I removed the uuid dependency in the build since it didn't seem to be needed - if there is some effect this has that I'm not aware of then let me know I can add it back in.

**Comment by ArthurSonzogni** [comment]
> Currently available at my nixpkgs fork, but hopefully it will be merged upstream soon.

Excellent! Thanks for working on this!

I don't know nix much. I know we now have a [flake.nix](https://github.com/ArthurSonzogni/FTXUI/pull/603) in FTXUI. Please let me know if there is a need to maintain something directly in this repository.

> I should mention that I removed the uuid dependency in the build since it didn't seem to be needed - if there is some effect this has that I'm not aware of then let me know I can add it back in.

I think you are right!
It was added as part of: https://github.com/ArthurSonzogni/Diagon/issues/26
This was a dependency in ANTLR, but it looks like it has been removed recently: https://github.com/antlr/antlr4/commit/0b8ed202e38137553364bfd84236c488c9460334

**Review by ArthurSonzogni — APPROVED** [review]
LGTM!

**Comment by petertrotman** [comment]
> Excellent! Thanks for working on this!

No problem, thank you for the program :-)

> Please let me know if there is a need to maintain something directly in this repository.

No, a flake in-repo is one way of defining a package but all I have done is translate the build instructions into nix. Basically it just automates cloning the dependencies and running make in a way that is reproducible for other nix users. If a future release requires a fix from my build script then I have volunteered to take that on myself.

All the best,

P

**Pull request merged**
